services:
  database:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: danubian_trade
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always